" vim: set ft=vimrc

syntax enable

set incsearch hlsearch

set number

set colorcolumn=80,100,120 scrolloff=5

set ruler rulerformat=%28(%l,%c%V%=%P%12.12y%)

set backspace=indent,eol,start

" color customizations
highlight ColorColumn ctermbg=DarkGray guibg=DarkGray

" vim variants
if has("mac")
    set guifont=InputMonoCondensed-Regular:h13
endif
if has("transparency")
    set transparency=20
endif
