local application = require('hs.application')
local ax = require('hs.axuielement')
local timer = require('hs.timer')
local watchable = require('hs.watchable')

-- hs.streamdeck.init(function (connected, deck)

--   deck:setButtonColor(1, hs.drawing.color.red)
--   deck:setButtonColor(2, { ["red"]=1.000, ["green"]=0.500, ["blue"]=0.000, ["alpha"]=1})
--   deck:setButtonColor(3, { ["red"]=1.000, ["green"]=1.000, ["blue"]=0.000, ["alpha"]=1})
--   deck:setButtonColor(4, hs.drawing.color.green)
--   deck:setButtonColor(5, hs.drawing.color.blue)
--   deck:setButtonColor(6, { ["red"]=1.000, ["green"]=0.500, ["blue"]=0.000, ["alpha"]=1})
--   deck:setButtonColor(7, { ["red"]=1.000, ["green"]=1.000, ["blue"]=0.000, ["alpha"]=1})
--   deck:setButtonColor(8, hs.drawing.color.green)
--   deck:setButtonColor(9, hs.drawing.color.blue)
--   deck:setButtonColor(10, { ["red"]=0.500, ["green"]=0.000, ["blue"]=1.000, ["alpha"]=1})
--   deck:setButtonColor(11, { ["red"]=1.000, ["green"]=1.000, ["blue"]=0.000, ["alpha"]=1})
--   deck:setButtonColor(12, hs.drawing.color.green)
--   deck:setButtonColor(13, hs.drawing.color.blue)
--   deck:setButtonColor(14, { ["red"]=0.500, ["green"]=0.000, ["blue"]=1.000, ["alpha"]=1})
--   deck:setButtonColor(15, { ["red"]=1.000, ["green"]=0.000, ["blue"]=1.000, ["alpha"]=1})
--   deck:buttonCallback(function (data, button, pressed)
--     print(button)
--     print(pressed)
--   end)
--   print(deck:buttonLayout())
-- end)
