#!/usr/bin/env bash
set -euo pipefail

exit_code="${1:-}"
PROMPTCOLOR="${PROMPTCOLOR:-0}"

short_root=${PWD#$REPOS_ROOT/}

prompt_color="\[\e[${PROMPTCOLOR};7m\]"
reset="\[\e[0m\]"
gray="\[\e[37m\]"
green="\[\e[32m\]"
blink="\[\e[5m\]"


# compute current version control system info for the working directory
function __vcsinfo {
  local git_branch

  git_branch="$(__git_current_branch)"
  case "${git_branch}" in
    "") echo -n "";;
    "main") echo -n "${gray}[main]${reset}";;
    "master") echo -n "${gray}[master]${reset}";;
    *) echo -n "${green}[${git_branch}]${reset}";;
  esac
}


function __git_current_branch {
  local ref
  ref="$(git symbolic-ref HEAD 2> /dev/null)" || return
  echo "${ref#refs/heads/}"
}

time_str="$(date +"%H%M%S")"
clock="${time_str:0:2}${blink}:${reset}${time_str:2:2}${blink}:${reset}${time_str:4:2}"

if [ "${exit_code}" == "0" ]; then
  _code="\[\e[47m\]   0 ${reset}"
else
  _code="\[\e[41m\] $(printf '% 3s' "${exit_code}") ${reset}"
fi
_path="📁 ${short_root}"

echo -e "${_code} ${clock}${reset} ${prompt_color}\\!${reset}:$(__vcsinfo) ${_path}${reset}\n\\$ "
