#!/usr/bin/env bash
#
# Return the Chrome profile directory that corresponds to the specified name.
set -euo pipefail

# Hammerspoon runs a very restricted PATH, but then we can't find jq
export PATH=$PATH:/usr/local/bin:/opt/homebrew/bin

if ! command -v jq >/dev/null; then
  echo "no jq! $PATH"
  exit 1
fi

profile_name="${1:-}"
export profile_name

is_profile_dir () {
  local prefsFile="$1/Preferences"
  [ -f "${prefsFile}" ] && if [ -z "${profile_name}" ]; then
    [ -n "$(jq -r .profile.name "${prefsFile}" 2>/dev/null)" ]
  else
    [ "${profile_name}" = "$(jq -r .profile.name "${prefsFile}" 2>/dev/null)" ]
  fi
}

export -f is_profile_dir

exec find "${HOME}/Library/Application Support/Google/Chrome" \
  -maxdepth 1 \
  -type d \
  -exec bash -c 'is_profile_dir "$0"' {} \; \
  -exec basename {} \;
