format = """
$status\
$time\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$directory\
$line_break\
$jobs\
$character
"""

[directory]
truncation_length = 100

[git_branch]
format = "[\\[$symbol$branch(:$remote_branch)\\]]($style) "
style = "green bold"

[status]
style = "bg:blue"
symbol = "🔴 "
success_symbol = "🟢 SUCCESS"
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[time]
style = ""
format = '[$time]($style) '
disabled = false
